version: '3.8'

services:
  mongo:
    image: mongo:latest
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - .env

  backend:
    image: alabosri/backend-image
    
    depends_on:
      - mongo
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    secrets:
      - mongo_uri_secret
    ports:
      - "5000:5000"
    networks:
      - mern_network

  frontend:
    image: alabosri/frontend-image
    networks:
      - mern_network
    depends_on:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    ports:
      - "3000:80"

secrets:
  mongo_uri_secret:
    external: true



volumes:
  mongo-data:

networks:
  mern_network:
    driver: overlay